In [12]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sqlalchemy import create_engine, text

In [13]:
engine = create_engine('postgresql+psycopg2://postgres:noi123456@noing-db.c2qkku433l07.ap-southeast-1.rds.amazonaws.com:5432/postgres')

In [14]:
with engine.connect() as conn:
    result = conn.execute(text('select * from movies'))
    movies = result.all()

In [15]:
movies_data = pd.DataFrame(movies)
movies_data

,movieId,title,genres,imdbId,tmdbId,plotSummary,releaseYear,posterPath,releaseDate,mpaa
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,"Led by Woody, Andy's toys live happily in his ...",1995,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,1995-10-30,G
1,2,Jumanji,Adventure|Children|Fantasy,113497,8844.0,When siblings Judy and Peter discover an encha...,1995,/vgpXmVaVyUL7GGiDeiK1mKEKzcX.jpg,1995-12-15,PG
2,3,Grumpier Old Men,Comedy|Romance,113228,15602.0,A family wedding reignites the ancient feud be...,1995,/1FSXpj5e8l4KH6nVFO5SPUeraOt.jpg,1995-12-22,PG-13
3,4,Waiting to Exhale,Comedy|Drama|Romance,114885,31357.0,"Cheated on, mistreated and stepped on, the wom...",1995,/4uw6HKq4vlhrSVp0zkgd4zCy4Pf.jpg,1995-12-22,R
4,5,Father of the Bride Part II,Comedy,113041,11862.0,Just when George Banks has recovered from his ...,1995,/rj4LBtwQ0uGrpBnCELr716Qo3mw.jpg,1995-12-08,PG
...,...,...,...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic,Action|Animation|Comedy|Fantasy,5476944,432131.0,"Ciel learns of a ""Aurora Society"", that is rum...",2017,/4jU2Bdk1MB2OvP4BBvTJIPQc0BF.jpg,2017-01-21,None
9738,193583,No Game No Life: Zero,Animation|Comedy|Fantasy,5914996,445030.0,"In ancient Disboard, Riku is an angry, young w...",2017,/cCBB6BGRj5nCTaEgogDtkHfjOLK.jpg,2017-07-15,R
9739,193585,Flint,Drama,6397426,479308.0,A woman deals with the toxic water scandal in ...,2017,/iPzkjNWpK7ud5pE997eGaB4QhaG.jpg,2017-10-28,
9740,193587,Bungo Stray Dogs: Dead Apple,Action|Animation,8391976,483455.0,A large scale catastrophe is occurring across ...,2018,/7ueB7Kxq2GObp5aDw6rsdzVefzP.jpg,2018-03-03,NC-17
9741,193609,Andrew Dice Clay: Dice Rules,Comedy,101726,37891.0,"Outrageous, misogynistic and vulgar-to-the-max...",1991,/isX74cYvlYVDyyiZKyDAfzz2Wkg.jpg,1991-05-17,R

In [16]:
genres = movies_data['genres'].str.split('|')
for i in range(len(genres)):
    genres[i] = ' '.join(map(str, genres[i]))

In [17]:
genres

0       Adventure Animation Children Comedy Fantasy
1                        Adventure Children Fantasy
2                                    Comedy Romance
3                              Comedy Drama Romance
4                                            Comedy
                           ...
9737                Action Animation Comedy Fantasy
9738                       Animation Comedy Fantasy
9739                                          Drama
9740                               Action Animation
9741                                         Comedy
Name: genres, Length: 9742, dtype: object

In [18]:
movies_data['genres'] = genres

In [19]:
movies_data

,movieId,title,genres,imdbId,tmdbId,plotSummary,releaseYear,posterPath,releaseDate,mpaa
0,1,Toy Story,Adventure Animation Children Comedy Fantasy,114709,862.0,"Led by Woody, Andy's toys live happily in his ...",1995,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,1995-10-30,G
1,2,Jumanji,Adventure Children Fantasy,113497,8844.0,When siblings Judy and Peter discover an encha...,1995,/vgpXmVaVyUL7GGiDeiK1mKEKzcX.jpg,1995-12-15,PG
2,3,Grumpier Old Men,Comedy Romance,113228,15602.0,A family wedding reignites the ancient feud be...,1995,/1FSXpj5e8l4KH6nVFO5SPUeraOt.jpg,1995-12-22,PG-13
3,4,Waiting to Exhale,Comedy Drama Romance,114885,31357.0,"Cheated on, mistreated and stepped on, the wom...",1995,/4uw6HKq4vlhrSVp0zkgd4zCy4Pf.jpg,1995-12-22,R
4,5,Father of the Bride Part II,Comedy,113041,11862.0,Just when George Banks has recovered from his ...,1995,/rj4LBtwQ0uGrpBnCELr716Qo3mw.jpg,1995-12-08,PG
...,...,...,...,...,...,...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic,Action Animation Comedy Fantasy,5476944,432131.0,"Ciel learns of a ""Aurora Society"", that is rum...",2017,/4jU2Bdk1MB2OvP4BBvTJIPQc0BF.jpg,2017-01-21,None
9738,193583,No Game No Life: Zero,Animation Comedy Fantasy,5914996,445030.0,"In ancient Disboard, Riku is an angry, young w...",2017,/cCBB6BGRj5nCTaEgogDtkHfjOLK.jpg,2017-07-15,R
9739,193585,Flint,Drama,6397426,479308.0,A woman deals with the toxic water scandal in ...,2017,/iPzkjNWpK7ud5pE997eGaB4QhaG.jpg,2017-10-28,
9740,193587,Bungo Stray Dogs: Dead Apple,Action Animation,8391976,483455.0,A large scale catastrophe is occurring across ...,2018,/7ueB7Kxq2GObp5aDw6rsdzVefzP.jpg,2018-03-03,NC-17
9741,193609,Andrew Dice Clay: Dice Rules,Comedy,101726,37891.0,"Outrageous, misogynistic and vulgar-to-the-max...",1991,/isX74cYvlYVDyyiZKyDAfzz2Wkg.jpg,1991-05-17,R

In [20]:
# number of rows and columns in the data frame
movies_data.shape

(9742, 10)

In [21]:
# selecting the relevant features for recommendation

selected_features = ['genres','mpaa']
print(selected_features)

['genres', 'mpaa']

In [22]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [39]:
# combining all the selected features

combined_features = movies_data['genres']+' '+movies_data['mpaa'] + ' '

In [40]:
print(combined_features)

0       Adventure Animation Children Comedy Fantasy G
1                       Adventure Children Fantasy PG
2                                Comedy Romance PG-13
3                              Comedy Drama Romance R
4                                           Comedy PG
                             ...
9737                 Action Animation Comedy Fantasy
9738                       Animation Comedy Fantasy R
9739                                           Drama
9740                           Action Animation NC-17
9741                                         Comedy R
Length: 9742, dtype: object

In [41]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [42]:
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 10)	0.482990142708577
  (0, 6)	0.26758647689140014
  (0, 5)	0.5048454681396087
  (0, 4)	0.5162254711770092
  (0, 3)	0.41684567364693936
  (1, 23)	0.34196301955605496
  (1, 10)	0.5578720893330542
  (1, 5)	0.5831158261780526
  (1, 3)	0.4814726975228866
  (2, 0)	0.5529247722475262
  (2, 24)	0.5783668519194922
  (2, 23)	0.44498555369972
  (2, 6)	0.40218632228646334
  (3, 9)	0.46640480307738325
  (3, 24)	0.726240982959826
  (3, 6)	0.5050154397005037
  (4, 23)	0.7418837606683695
  (4, 6)	0.6705285121876307
  (5, 26)	0.5420423542868653
  (5, 7)	0.6359470441562756
  (5, 2)	0.5493281743985542
  (6, 24)	0.694125312504764
  (6, 23)	0.5340481313837788
  (6, 6)	0.4826827570005564
  (7, 23)	0.41203990560377823
  :	:
  (9732, 11)	0.48136743695078876
  (9732, 25)	0.48136743695078876
  (9732, 2)	0.39038039438445316
  (9732, 6)	0.28524046407869114
  (9732, 4)	0.5502833875552382
  (9733, 22)	0.6598488082788799
  (9733, 9)	0.32444911497282136
  (9733, 4)	0.6777406008247512
  (9734, 9)	0.6784659961265057
  (9734, 6)	0.7346318071660581
  (9735, 4)	1.0
  (9736, 8)	1.0
  (9737, 2)	0.4360100100175108
  (9737, 10)	0.5750342353604592
  (9737, 6)	0.31858079808657136
  (9737, 4)	0.614603265870322
  (9738, 10)	0.6389682371675297
  (9738, 6)	0.35400155057063365
  (9738, 4)	0.682936669160916
  (9739, 9)	1.0
  (9740, 1)	0.6353743032963398
  (9740, 19)	0.6353743032963398
  (9740, 2)	0.2539275036763273
  (9740, 4)	0.35793828001219785
  (9741, 6)	1.0

In [43]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.76452991 0.10761962 ... 0.         0.18477686 0.26758648]
 [0.76452991 1.         0.1521686  ... 0.         0.         0.        ]
 [0.10761962 0.1521686  1.         ... 0.         0.         0.40218632]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.18477686 0.         0.         ... 0.         1.         0.        ]
 [0.26758648 0.         0.40218632 ... 0.         0.         1.        ]]

In [44]:
print(similarity.shape)

(9742, 9742)

In [45]:
# getting the movie name from the user
movie_name = input(' Enter your favourite movie name : ')

# creating a list with all the movie names given in the dataset
list_of_all_titles = movies_data['title'].tolist()

# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)
close_match = find_close_match[0]

# finding the index of the movie with title
id_of_the_movie = movies_data[movies_data.title == close_match]['movieId'].values[0]
index_of_the_movie = movies_data.index[movies_data['movieId']==id_of_the_movie].tolist()[0]

# getting a list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))

# sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

# print the name of similar movies based on the index
print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<60):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : Toy Story
['Toy Story', 'Toy Story 3', 'Toy Story 2']
Movies suggested for you :

1 . Toy Story
2 . Toy Story 2
3 . The Emperor's New Groove
4 . Monsters, Inc.
5 . The Wild
6 . The Tale of Despereaux
7 . We're Back! A Dinosaur's Story
8 . The Land Before Time
9 . Sinbad: Legend of the Seven Seas
10 . The Phantom Tollbooth
11 . Kirikou and the Sorceress
12 . The Cat Returns
13 . Ponyo
14 . Vovka in the Kingdom of Far Far Away
15 . Antz
16 . The Adventures of Rocky & Bullwinkle
17 . Shrek the Third
18 . Turbo
19 . The Good Dinosaur
20 . Moana
21 . The Twelve Tasks of Asterix
22 . Little Nemo: Adventures in Slumberland
23 . Kiki's Delivery Service
24 . Gnomeo & Juliet
25 . The Wonderful World of Puss 'n Boots
26 . Inside Out
27 . The Black Cauldron
28 . The Lord of the Rings
29 . Atlantis: The Lost Empire
30 . PokÃ©mon 4Ever
31 . Kubo and the Two Strings
32 . Partly Cloudy
33 . Presto
34 . Stuart Little 3: Call of the Wild
35 . Last Year's Snow Was Falling
36 . Wow! A Talking Fish!
37 . TMNT
38 . The Lego Movie
39 . The Pagemaster
40 . Shrek
41 . Watership Down
42 . Asterix and the Vikings
43 . All Dogs Go to Heaven
44 . An American Tail
45 . A Bug's Life
46 . Jimmy Neutron: Boy Genius
47 . Finding Nemo
48 . The Lion King 1Â½
49 . Wallace & Gromit: The Curse of the Were-Rabbit
50 . Curious George
51 . Horton Hears a Who!
52 . Rio
53 . Asterix Conquers America
54 . Rio 2
55 . The Fox and the Hound 2
56 . The Peanuts Movie
57 . Thumbelina
58 . The Care Bears Movie
59 . The Last Unicorn